# Runs on completion (success or fail) of specified workflows
name: Completion
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Test
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
      - uses: actions/checkout@v4
      - uses: ./.github/actions/print-job
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: octokit/request-action@v2.x
        id: dispatch_failure
        with:
          route: POST /repos/${{ github.repository }}/actions/workflows/failure.yml/dispatches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
      - run: "echo github_api_output: '${{ steps.dispatch_failure.outputs.data }}'"