# Runs on completion (success or fail) of specified workflows
name: Completion
on:
  workflow_run:
    branches: # The important branches
      - main
    workflows: # The important workflows
      - Test 
      - Release
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'Things went well'
  on-failure:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: octokit/request-action@v2.x
        id: dispatch_failure
        with:
          route: POST /repos/${{ github.repository }}/actions/workflows/failure.yml/dispatches
          ref: 'main'
          inputs: '{}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}