# Simply a failure workflow which can be subscribed to e.g. by the Slack GitHub bot
# (why is this needed? https://github.com/integrations/slack/issues/1563)
#
# This is dispatched via GitHub REST API in the 'Completion' workflow
name: Failure
on:
  workflow_dispatch:

jobs:
  failure-reporting-job:
    runs-on: ubuntu-latest
    steps:
      # Do nothing, unsuccessfully
      - run: false 